services:
  - type: web
    name: stopwatch-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: stopwatch-db
          property: connectionString

databases:
  - name: stopwatch-db
    databaseName: stopwatch
    user: stopwatch
    plan: free